version: "3"
services:
  postgres:
    image: library/postgres:13
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"

  rental-service:
    image: rental-service
    container_name: rental-service
    restart: on-failure
    build:
      context: src
      dockerfile: rental-service/Dockerfile
    ports:
      - "8060:8060"
    depends_on:
      - postgres

  payments-service:
    image: payments-service
    container_name: payments-service
    restart: on-failure
    build:
      context: src
      dockerfile: payments-service/Dockerfile
    ports:
      - "8050:8050"
    depends_on:
      - postgres

  cars-service:
    image: cars-service
    container_name: cars-service
    restart: on-failure
    build:
      context: src
      dockerfile: cars-service/Dockerfile
    ports:
      - "8070:8070"
    depends_on:
      - postgres

  api-gateway:
    image: api-gateway
    container_name: api-gateway
    restart: on-failure
    build:
      context: src
      dockerfile: api-gateway/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - rental-service
      - payments-service
      - cars-service

volumes:
  db-data: