name: GitHub Classroom Workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: docker/setup-buildx-action@v2

      - name: Build images
        timeout-minutes: 10
        run: |
          docker-compose build postgres
          docker-compose build api-gateway
          docker-compose build rental-service
          docker-compose build payments-service
          docker-compose build cars-service
      - name: Setup db
        run: |
          docker-compose up -d postgres
          docker-compose logs postgres
          sleep 5
          cd postgres
          ./30-create_test_database.sh
          cd ..

      - name: Run containers
        timeout-minutes: 10
        run: |
          docker-compose up -d rabbitmq
          docker-compose up -d rental-service
          docker-compose up -d payments-service
          docker-compose up -d cars-service
          docker-compose up -d api-gateway
          docker-compose up -d cancel-rent-broker

          docker-compose logs rental-service
          docker-compose logs payments-service
          docker-compose logs cars-service
          docker-compose logs api-gateway
          ./scripts/wait-script.sh
        env:
          WAIT_PORTS: 8080,8070,8060,8050

      - name: Run API Tests
        timeout-minutes: 5
        run: ./scripts/test-script.sh
      #  env:
      #    VARIANT: <variant>
      #    SERVICE_NAME: <your service name>
      #    PORT_NUMBER: <port number>

      # - uses: education/autograding@v1
      #   id: autograder
      #   continue-on-error: true

      # - name: Github auto grader mark
      #   uses: Romanow/google-sheet-autograder-marker@v1.0
      #   with:
      #     google_token: ${{secrets.GOOGLE_API_KEY}}
      #     sheet_id: "1xkgjUX6Qmk7rdJG-QPOToav-HWWtthJjnShIKnw3oIY"
      #     homework_number: 2
      #     user_column: 'D'
      #     column_offset: 'F'
      #     mark: "'+"

      - name: Stop containers
        if: always()
        continue-on-error: true
        run: docker compose down -v